### ISSUE TITLE
Alternative way to deal with versioning?

### ISSUE THREAD

**Issue by Ashvith10** [alexghr/turborepo.nix#5]
Currently, the turborepo flake uses the `inputs.turbo.url = "github:alexghr/turborepo.nix/v${version}";`, which isn't convenient for a monorepo that is growing in size, as the flakes have to be manually updated. I was wondering if it is possible to use string interpolation to extract value of turbo from `package.json`? The `version` variable can be set by the user to parse either the package.json or the lock files. Since this isn't possible in `inputs`, perhaps this could be done in `outputs`?

**Comment by alexghr** [comment]
That's a good question. I haven't considered it this way. My use case for this has been to 'pin' the exact version of turborepo in `package.json` and `flake.nix` and ensuring they're updated in lockstep.

We could export a library function from this flakes that takes a turborepo version and generates a derivation for it, but it would fall upon the user of the flake to provide an appropriate `sha256` for the sources (without sha256 Nix can't ensure purity) so it makes things even more difficult.

I think a better approach would to see if we can avoid having to depend upon `turbo` in `package.json` entirely. AFAIK the `turbo` npm package is just a thin wrapper around the actual Go binary that does the initial installation (based on os/architecture). Nix already handles installing the right binary, we might be able to use it directly and bypass npm. 

I'll do some testing and get back to you on this issue.

**Comment by alexghr** [comment]
hey @Ashvith10. I had a play with just declaring `turbo` as a flake input, without adding it to `package.json` and it does work. Everything you'd use turbo for (including the daemon) works as expected. The problem is if the project has developers that don't use the Nix development shell then `turbo` won't be available in their shell.

I'll leave this ticket open if anyone wants to contribute ideas to solve it. I can't think of anything that would have better UX than declaring `turbo` just in the Nix dev shell (and ensuring all devs use Nix) or declaring `turbo` in both `package.json` and `flake.nix` and keeping the two versions in sync.

**Comment by Ashvith10** [comment]
@alexghr How about using `@pnpm/lockfile-file` to read version from the lockfile? It can read for all three package managers: npm, yarn and pnpm. What do you think? The only issue would be that if we try to update inside the flake environment, it might probably brick, unless there's a shell-hook we can run after every command is run to verify if package lockfile and flake Turbo binaries use the same version. What do you say?

**Comment by alexghr** [comment]
Hey, sorry for ghosting you (for almost two months :scream:). using `@pnpm/lockfile-file` sounds like a good idea. How would you check that the version matches the input in `flake.nix`? Or would this check that `turbo --version` matches the expected version in the lockfile?

I think this is great addition to this flake but I'd keep it as a separate installable so people that want to just use a pinned version can continue doing so and people that want to track the turborepo version from their lockfile can use this approach. WDYT?

**Comment by Ashvith10** [comment]
@alexghr I've not worked on this myself, and I'm also not a flake or nix expert, but from examples I've seen, like the DotNET module (using Shellscript) and Vim plugin system (using Python), you're gonna have to generate a custom Nix file in the directory using a programming language of your choice.

I am not sure if "meta-programming" is the right word to use here, but something like that, I guess. [Here's one such example](https://github.com/NixOS/nixpkgs/blob/72457c9fc55af797f2bafe9ea82f749bc8a24750/pkgs/applications/editors/vim/plugins/update.py#L53) - essentially, we are automating packaging the plugins for Vim, but similar stuff can be done in this case as well - we might want to generate the `package.nix` file, which is referenced by the `flake.nix` file?
